### ISSUE TITLE
OH - Dashboard | Melhorar sistema de login (Firebase)

### ISSUE THREAD

**Issue by Yagasaki7K** [KalifyInc/board-kalify#19]

**Comment by gabrielUpON** [comment]
Firebase authentication methods have been created. Waiting for the creation of SignIn and SignOut pages.

**Comment by Yagasaki7K** [comment]
SignIn is a login page using actually with OnigiriHardcore. You just remove inputs and use a button from Google.
And SignOut is actually "Sair" on dashboard, him is a logout.

And only when the user click in logout he will be logoff. If change the page doesnt.

**Comment by gabrielUpON** [comment]
Finished

More details [59edc40](https://github.com/Yagasaki7K/website-onigirihardcore/commit/59edc4072506c846d1094b3b089e076aa7975c39) e [e7a1880](https://github.com/Yagasaki7K/website-onigirihardcore/commit/e7a1880077d174278e15e4e3f9b9a537760eb956).
